services:
  perlite:
    image: sec77/perlite:latest
    container_name: perlite
    restart: unless-stopped
    environment:
      - NOTES_PATH=Privat
      - HIDE_FOLDERS=docs,private,trash
      - LINE_BREAKS=true
      - ABSOLUTE_PATHS=false
      - ALLOWED_FILE_LINK_TYPES=pdf,mp4,json
      - DISABLE_POP_HOVER=false
      - SHOW_TOC=true
      - SHOW_LOCAL_GRAPH=true
      - HOME_FILE=README
      - FONT_SIZE=15
      - HTML_SAFE_MODE=true
      - TEMP_PATH=/tmp
      - SITE_TITLE=Ob-Ivan´s Obsidian
      - SITE_TYPE=article
      - SITE_URL=https://notes.obivan.org
      - SITE_IMAGE=
      - SITE_DESC=
      - SITE_NAME=Ob-Ivan´s Obsidian
      - SITE_TWITTER=https://x.com/
      - SITE_LOGO=perlite.svg
      - SITE_HOMEPAGE=https://casa.obivan.org
      - SITE_GITHUB=https://github.com/
    volumes:
      - /mnt/storagebox/storage/documents/notes:/var/www/perlite/Privat:ro

  web:
    image: nginx:stable
    container_name: perlite_web
    restart: unless-stopped
    ports:
      - 8088:80
    volumes:
      - ./web/config/perlite.conf:/etc/nginx/conf.d/default.conf:ro
    volumes_from: 
      - perlite        
    depends_on:
      - perlite

  git-sync:
    build: .
    container_name: git_sync
    restart: unless-stopped
    volumes:
      - /mnt/storagebox/storage/documents/notes:/var/www/perlite/Privat
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - perlite
